version: '3.8'


services:
  proxy:

    build:
      context: proxy
      dockerfile: ./Dockerfile
    
    restart: unless-stopped

    ports:
    - "80:80"
    - "443:443"

  python:
    build:
      context: python
      dockerfile: ./Dockerfile

    restart: unless-stopped

    # ports:
    #   - "8888:8888"
