version: '3.8'


services:
  proxy:
    image: nginx:1.28.0-alpine-slim
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']

    ports:
    - "80:80"
    - "443:443"

  python:
    build:
      context: python
      dockerfile: ./Dockerfile

    restart: unless-stopped

    # ports:
    #   - "8888:8888"
