name: Deploy Tag (manually)

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: The repository tag reference to be deployed
        type: string

jobs:
  deploy_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./python
    
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/curso_devops_api_receitas_python:${{ inputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: Verify tag existence
        # The checkout step can still work if for some reason there is a branch with said name
        run: |
            if git show-ref --tags --verify --quiet "refs/tags/${{ inputs.tag }}"; then
                echo Tag exists
            else
                echo Tag not found. Input a tag that exists.
                exit 1
            fi
          
      - name: Deploy to azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: eddcorts-gh-actions-python
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_NAME }}