name: Deploy Tag (manually)

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: The repository tag reference to be deployed
        type: string

jobs:
  deploy_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./python
    
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/curso_devops_api_receitas_python:${{ inputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.tag }}"
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }} --file Dockerfile .
      
      - name: Push image to DockerHub
        run: docker push ${{ env.IMAGE_NAME }}
          
      - name: Deploy to azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: eddcorts-gh-actions-python
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_NAME }}