name: Lint Project

on:
  pull_request:
    branches: [main]
  issue_comment: 
    types: [created]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installs Poetry
        run: pipx install poetry

      # Language configuration
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: Install dependencies
        run: poetry install --with dev --no-root
      
      - name: Linting
        run: poetry run poe pre_commit_all



